<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDkS38vq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDkS38vq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDkS38vq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDkS38vq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDkS38vq\App_KernelDevDebugContainer([
    'container.build_hash' => 'DkS38vq',
    'container.build_id' => 'f738938b',
    'container.build_time' => 1714299982,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDkS38vq');
