spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo
  
server:
  port: 8083

camunda:
  bpm:
    generic-properties:
      properties:
        historyTimeToLive: P30D