controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

accueil:
    path: /accuiel
    controller: App\Controller\ProductController::index

client:
    path: /client
    controller: App\Controller\ClientController::index



